apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-web-deploy
  labels:
    app: health-centre-web
spec:
  replicas: 2  # Running 2 copies right away for basic high availability
  selector:
    matchLabels:
      app: health-centre-web
  template:
    metadata:
      labels:
        app: health-centre-web
    spec:
      containers:
      - name: nginx
        image: findash.azurecr.io/health-centre-web:v2
        ports:
        - containerPort: 80
        # Defining resource boundaries (good practice even without HPA)
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
