apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-web-deploy
  labels:
    app: health-centre-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-centre-web
  template:
    metadata:
      labels:
        app: health-centre-web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine   # <--- CHANGE 1: Use the public Nginx image
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        # CHANGE 2: Mount the ConfigMap volume here
        volumeMounts:
        - name: web-files
          mountPath: /usr/share/nginx/html  # Nginx's default web directory
      # CHANGE 3: Define the volume that uses the ConfigMap
      volumes:
      - name: web-files
        configMap:
          name: health-web-config   # The name of the ConfigMap you'll create
